Sprint 2/step 2
iShangareev/react-burger pull request #4
Opened 2022-12-25 14:31 UTC by iShangareev

2022-12-25 18:12 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали хорошую работу по добавлению DnD и Редакса в ваш проект, необходимый функционал работает практически корректно, присутствует переключение табов в списке ингредиентов, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- **Каждый PR** одобренный ранее ревьюерами, который сейчас находится в вашем репозитории, за исключением текущего (последнего), **следует влить в ветку main**, согласно требованию, указанному в конце формулировки каждого задания: `Как только работа будет зачтена, нажмите кнопку Merge, чтобы применить изменения из ветки ... в ветку main`. 
- При отсутствии элементов конструкторе не следует отображать счётчик равный нулю, его необходимо скрыть (см. https://disk.yandex.ru/i/184mrf66u5AdSQ);
- В массиве ингредиентов, который отправляется на сервер, следует добавить два ID булки - один в начало, другой в конец, как они расположены в конструкторе;
- Следует убрать возможность оформления заказа и открытие соответствующего модального окна без ингредиентов в конструкторе (при этом заказ из одних булок является допустимым), см. https://disk.yandex.ru/i/LndTTJ6whfO3xg;
- Следует разделить экшены и редьюсеры по файлам, каждый из которых отвечает за отдельную область вашего проекта (получение ингредиентов, создание заказа и т.д.);
- Следует скорректировать работу с `useMemo` в конструкторе (подробнее в комментарии в файле);

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-12-25 18:12 UTC, randomroot commented on src/components/order-details/order-details.jsx
> +    data: PropTypes.object,
🔴 **Нужно исправить:**

Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredient-item.jsx
> +    const[count, setCount] = useState()
🟡 **Можно улучшить:**

Целесообразно указать начальное значение равное нулю

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredient-item.jsx
> +    const { _id, name,price,image,type } = props.data
🟡 **Можно улучшить:**

Декомпозицию можно перенести наверх в скобки, вместо `(props)`

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredient-item.jsx
> +    },[constructorIngredients, bun])
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2022-12-25 18:12 UTC, randomroot commented on src/services/actions/actions.js
> +
🔴 **Нужно исправить:**

Cледует разделить экшены по файлам, у нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2022-12-25 18:12 UTC, randomroot commented on src/services/actions/actions.js
> +     dispatch({
🟡 **Можно улучшить:**

Имеет смысл проверять также и в теле ответа `response.ok`, т.к. эта логическая переменная в ответе может быть со значением `false`

2022-12-25 18:12 UTC, randomroot commented on src/services/actions/actions.js
> +      dispatch({
🟡 **Можно улучшить:**

Имеет смысл перенести процесс сортировки непосредственно в редьюсер, чтобы не передавать состояние стора через несколько узлов до этой функции, а работать с ним напрямую

2022-12-25 18:12 UTC, randomroot commented on src/services/reducers/reducer.js
> +export const reducer = (state = initialState, action) => {
🔴 **Нужно исправить:**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2022-12-25 18:12 UTC, randomroot commented on src/services/reducers/reducer.js
> +        fetchRequest: false
🔴 **Нужно исправить:**

Для каждой группы запросов следует сделать отдельную переменную их состояния (получение ингредиентов/отправка заказа)

2022-12-25 18:12 UTC, randomroot commented on src/services/reducers/reducer.js
> +  ingredient: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2022-12-25 18:12 UTC, randomroot commented on src/services/reducers/reducer.js
> +          constructorIngredients: [...state.constructorIngredients].filter(item => item.ingredientUuid !== action.payload)
🔴 **Нужно исправить:**

Т.к. функция `filter` согласно документации возвращает новый массив, то делать копию самостоятельно не следует

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <IngredientDetails></IngredientDetails>
🟡 **Можно улучшить:**

В таких случаях целесообразно использовать синтаксис самозакрывающихся тегов `<IngredientDetails />`

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <>
🔴 **Нужно исправить:**

React.Fragment здесь лишний, вы можете разместить подряд несколько HTML элементов, главное чтобы у них был единый родитель

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <>
🟡 **Можно улучшить:**

У категорий ингредиентов сходный исходный код, поэтому целесообразно вынести их в отдельный компонент, настраиваемый через пропсы чтобы уменьшить дублирование кода

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const [currentTab, setCurrentTab] = useState("bun")
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const getIdIngredients = useMemo(
🔴 **Нужно исправить:**

Переменные с `useMemo` не используется в коде напрямую (см. https://disk.yandex.ru/i/jGgvSxRMkCfaYQ).
И хотя подсчёты ведутся за счёт вызова функций при каждом рендере (т.к. в хуке не указан массив зависимостей), это некорректный подход. 
Для `useMemo` примером правильного использования может послужить расчёт стоимости ингредиентов с использованием функции `reduce` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce): 
```js
const price = useMemo(() =>  сonstructorIngredients.reduce((acc, item) => acc + item.price, bun.price * 2), [сonstructorIngredients, bun])
```

Попробуйте скорректировать ваши функции и переменные.

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        constructorIngredients.filter(element => ingredientsId.push(element._id)),
🔴 **Нужно исправить:**

В данном случае следует использовать функцию `map` `ingredientsId = constIng.map(...)` или заменить `filter`, генерирующий новый массив на `forEach`, который просто проходит по массиву

2022-12-25 18:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        {if(bun) ingredientsId.push(bun._id)},
🟡 **Можно улучшить:**

Массив ингредиентов для заказа целесообразно генерировать в момент его создания, чтобы не использовать дополнительную память при каждом рендеринге

2022-12-26 14:00 UTC, iShangareev commented on src/components/order-details/order-details.jsx
> +    data: PropTypes.object,
Данные теперь забираю со стора

2022-12-28 13:27 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-13 18:07 UTC, merged